### ISSUE TITLE
Unable to download MessageSDKFramework

### ISSUE THREAD

**Issue by ikishanoza** [anantgarg/ios-objective-c-chat-sdk-demo#1]
I am trying to install pods but its stuck in between while downloading the `MessageSDKFramework` zip file.
so I manually download  and added in my pods that's fine but now I am unable to find `comechat-ui` pod..

do u have any url for `cometchat-ui` pod so I can manually download and add to my project ?

**Comment by jeetkapadia** [comment]
Hello,

We have checked and we are able to download the frameworks from pods however we have uploaded the frameworks on the below URL:

https://temp.cometchat.com/IOS_SDK_7_13_1.zip

Thanks
