### ISSUE TITLE
Settings screen: I want to change title, font, icons, hide few sections.

### ISSUE THREAD

**Issue by IMDGhanshyam** [anantgarg/ios-objective-c-chat-sdk-demo#10]
Hello,

Can we change the `title`, `fonts`, `icons` available in _Settings Screen_?
Even, I want to disable **View Profile** and **Bots** section from _Settings Screen_.

![screenshot 2018-12-06 at 2 33 38 pm](https://user-images.githubusercontent.com/44672948/49573687-a1b77200-f964-11e8-824b-7df6bf7b3fef.png)

Please advise on this.

**Comment by jigar-shethia01** [comment]
Hello,

Please refer to the attached documentation. This will resolve the issues you are facing.
Do let us know if you are still facing any issue. We'll be glad to assist you.

Thanks.

[Documentation.docx](https://github.com/CometChat/ios-objective-c-chat-sdk-demo/files/2657566/Documentation.docx)
