### ISSUE TITLE
Chat screen scroll performance.

### ISSUE THREAD

**Issue by IMDGhanshyam** [anantgarg/ios-objective-c-chat-sdk-demo#11]
When we scroll the chat screen, the performance is laggy. 

![abc](https://user-images.githubusercontent.com/44672948/49576698-c5ca8180-f96b-11e8-877f-399f5fee5221.png)

Can you advise to improve performance?

**Comment by vikrantwadate** [comment]
Hello,

Thanks for writing in. 

We will test the scenario mentioned by you at our end and help you with an update.

Thanks.

**Comment by jigar-shethia01** [comment]
Hello,

We have tested the issue you were facing and it seems that the chat screen scroll is working fine. Please refer to the attached video for the same.

[Screen Record.mp4.zip](https://github.com/CometChat/ios-objective-c-chat-sdk-demo/files/2735678/Screen.Record.mp4.zip)

If you still have any query or concern please let us know.

Thanks.
