### ISSUE TITLE
Need to open my own view controller, by tapping on "View Profile".

### ISSUE THREAD

**Issue by IMDGhanshyam** [anantgarg/ios-objective-c-chat-sdk-demo#12]
Is it possible to open my own view controller by tapping on **View Profile**?
Please find following reference screenshot.

![rea](https://user-images.githubusercontent.com/44672948/49577367-3f16a400-f96d-11e8-8452-f3cecd78a414.png)

Please advise on this.

Thanks.

**Comment by vikrantwadate** [comment]
Hello,

We will suggest you book a session with us so that we can answer what all queries you have and what exactly you are trying to achieve.

You can book a session with us using the link below :

https://www.cometchat.com/schedule-session/

Thanks.
