### ISSUE TITLE
Remove text of "has invited you to join a video conference"

### ISSUE THREAD

**Issue by IMDGhanshyam** [anantgarg/ios-objective-c-chat-sdk-demo#13]
Why does it say in iOS “has invited you to join a video conference”? 

I want to remove or change the text

![chat](https://user-images.githubusercontent.com/44672948/50139851-e0381f80-02c8-11e9-8060-88ce1b443744.png)

I want to change the text of "Leave Group"

![leavegroup](https://user-images.githubusercontent.com/44672948/50139964-360cc780-02c9-11e9-800b-4a1f59bb108a.png)

**Comment by jigar-shethia01** [comment]
Hello,

Thanks for writing in.

We will test the issue mentioned by you at our end and help you with an update.

Thanks.

**Comment by jigar-shethia01** [comment]
Hello,

We have checked this issue and we are unable to reproduce the same. Please provide us with the proper scenario to reproduce the issue.

Thanks.
