### ISSUE TITLE
No Language Found for KEY

### ISSUE THREAD

**Issue by IMDGhanshyam** [anantgarg/ios-objective-c-chat-sdk-demo#14]
When you create an Audio File, it works and sends but it shows this message before you send which is confusing. If I click type your message it sends the message and not sure what the No Language Found for KEY means.

![no language found for key](https://user-images.githubusercontent.com/44672948/50142337-e1b91600-02cf-11e9-8494-c9a65f1b4d14.png)

**Comment by vikrantwadate** [comment]
Hello,

Thanks for writing in.

We will test the scenario mentioned by you at our end and help you with an update.

Thanks.

**Comment by jigar-shethia01** [comment]
Hello,

We have checked this issue and we are unable to reproduce the same. Please provide us with the proper scenario to reproduce the issue.

Thanks.
