### ISSUE TITLE
<br> tags displayed in the message body.

### ISSUE THREAD

**Issue by IMDGhanshyam** [anantgarg/ios-objective-c-chat-sdk-demo#2]
Whenever I am sent the message with multiple lines, it was displayed with **<br>** tags do not take **"\n or newline"**
I have raised a support ticket from the www.cometchat.com/contact-support, but I did not get any response from them.

![br tags](https://user-images.githubusercontent.com/44672948/47854041-b43f0880-de06-11e8-9702-4c367c08caea.png)

**Comment by jitvarpatil** [comment]
Hello,
Thank you for contacting us. We are glad to inform you that we have already fixed this issue and is QA phase. It will be available you in v7.20.0

**Comment by IMDGhanshyam** [comment]
Thank you very much!

I want to disable group chat in the my iOS app. Can you please give me the steps to disable it. 



Ghanshyam Bhesaniya
Sr. iOS Developer
Website: http://email.imobdevtech.com/c/eJwtjktuwzAMRE9j72xI1IfSQgu3ju9BkVJsIEGCwK3R21f5DGY1i_dGUpSgM_VbCiG4WYEaYAlusNachmlepuF7sQbNCa2b586q7XrLUn5Hvl37NRWrwKNHMKxtZYqsIbOvpoaq2ef-ktZ9v3dm6mBpPY5j_BD2wuuL8kiPcr_8dfClgCJhtshOUEIlRKqOTGYTvEDxRQSdxtqMIllF4Kre0W11mshGIO0jF-3bCwbfLr_w43nb15_8NP4DN89HKg <http://email.imobdevtech.com/c/eJwtjsFugzAQRL8GbiB7vfauDz7QEv7D3rULUqJEES3q35e0Hc3pHd6MpqhsS-63xMx-NmAGWNgPiO4yTPMyDe8LOnIXQj_PHZrtdi9av0a53_o1WQpi0ApqZi0oZFEB2bPUKkihv6Z13x-dmzpYzh7HMf4b9irry3LS_pme9XH97uDNQI6ZCpJ4JeWWiXLz2RVxHBRqqKrkLTUKpFpMBGnmL_ak3uaMEbINUaoNoTmBcL7-1Y8f275-ltfoD9j4R5s>
SkypeID: ghanshyam.bhesaniya@imobdev.com <mailto:ghanshyam.bhesaniya@imobdev.com>
Office: +91-79-651-22300
United States: +1 (908) 301-6001








"PLEASE CONSIDER THE ENVIRONMENT BEFORE PRINTING THIS EMAIL"

**Comment by jeetkapadia** [comment]
Hello,
We have already made the fix live in v7.19.0. Please update the CometChat SDK to latest version(7.19.0) to get the fix.
