### ISSUE TITLE
Notification is not working in iOS

### ISSUE THREAD

**Issue by IMDGhanshyam** [anantgarg/ios-objective-c-chat-sdk-demo#3]
I have a setup everything for notification in the firebase and Cometchat CPanel but still not get any notification in background mode or inactive mode.

# SDK Version
- MessageSDKFramework 7.20.0
- cometchat-ui 7.20.0

**Comment by jeetkapadia** [comment]
Hi,

Please refer the below documentation to setup Firebase Push Notifications in iOS:

https://developer.cometchat.com/docs/ios-push-notifications

Also, make sure you add the Firebase Legacy server key in CometChat Admin Panel -> Settings -> Mobile -> Firebase server key.

Thanks

**Comment by IMDGhanshyam** [comment]
Everything was setup from my side as it is mention in http://email.imobdevtech.com/c/eJwlj0tuwzAMRE9j7xyINKPPwgsrae6hD1ULcCLDVgL09pVbYgA-cMABGScTNXjX58kaq2aJdlB3UgPpRrOQt-Ghxf1m5y_ShB2J_Cw-8ucSyrNfJvIUhUiMYdQYAEank5YJkpQKNXO_Tkut29GNc4ePprbKa9l4PwO4hsXVk06nhKO1XI5hex_L8Co1pxxczeV19Pu087b-dGgFOuOUJ0TlTzAmkk8SEEMCmUZyFAQyQIyJGIxpc_FfAFpc6eqcQQfSBAbpNVGU7a-_-Mt3rsvbnxf9AoXHU_w <http://email.imobdevtech.com/c/eJwlj0tuwzAMRE9j7xyINKPPwgsrae6hD1ULcCLDVgL09pVbYgA-cMABGScTNXjX58kaq2aJdlB3UgPpRrOQt-Ghxf1m5y_ShB2J_Cw-8ucSyrNfJvIUhUiMYdQYAEank5YJkpQKNXO_Tkut29GNc4ePprbKa9l4PwO4hsXVk06nhKO1XI5hex_L8Co1pxxczeV19Pu087b-dGgFOuOUJ0TlTzAmkk8SEEMCmUZyFAQyQIyJGIxpc_FfAFpc6eqcQQfSBAbpNVGU7a-_-Mt3rsvbnxf9AoXHU_w>. 
But it’s not working.  That way I have raised the ticket.

Please check the below screenshot

# APN’s certificates uploaded 




# The firebase key was inserted in the "Firebase server key”





Ghanshyam Bhesaniya
Sr. iOS Developer
Website: http://email.imobdevtech.com/c/eJwtjkuOwkAMRE-T7BK1jfvjRRZpGO5h92cSCQRCmYm4PQ0zJS9KJdVz5YlzAJV-nSJHPzuMgz-RHyg0Nxt3HM7BnI5x_qJA2JFZrzfN5XdMt2u_tLYqgmVna2vYLDU7ZlCVVBhR-su0bNu9O8wdntvt-z7-E7aSlg_lMT3K_fLsMBoUFq-E6PVtmDNpdYCYKrh6IKFksADkXKkAc8vNnwCCsWRFGAUcpwJOA1F2bfIHP36v2_Kj748vNURGnQ <http://email.imobdevtech.com/c/eJwtjkuOgzAQRE8DO5C7adruhRc4n3v4OyAFJYpIUG4fMzOlWpRq8aqSlWQg-HaxTpyeGF2nz6Q7MjVNik_d1ajzyU0XMoQNqWW9h5Tffbyv7WyHQmDyAAyC4IuokkfvNXseC2jF7c3O2_ZohqnBa_W-7_0_YctxPii1bZ_2mR-3T4NOoRevAyHqcASRRKEwIMYCXAbyFBVmgJQKZRCpvfoTgFEj1XlBDywxAwdDlLi-_sX3P8s2v8Ix-gVtJEZy>
SkypeID: ghanshyam.bhesaniya@imobdev.com <mailto:ghanshyam.bhesaniya@imobdev.com>
Office: +91-79-651-22300
United States: +1 (908) 301-6001








"PLEASE CONSIDER THE ENVIRONMENT BEFORE PRINTING THIS EMAIL"

**Comment by jeetkapadia** [comment]
I will check and will revert it on GitHub.

**Comment by IMDGhanshyam** [comment]
Is there any updated for me?



Ghanshyam Bhesaniya
Sr. iOS Developer
Website: http://email.imobdevtech.com/c/eJwtjkluwzAMRU9j72yIEjVwoYXsRvcQNdQGEiQI3Bq9fZW0BAl8_MV7LJ6KA07j7km5y4dd3GRsWCa0ap0orjjZENY1hqgwXgYU--3OpX7P-X4bNy9zc5a11twcJ8mV-4mkrFBgWajx6rfjeAwqDDL2Pc9z_iccNW9vytM_6-P6M8hFyETJMkpp-RWICnIzILsGTFOYMAtZAUppWIGo9-JvAJzQqFMimcBQrmDYIRbTX37j58_92L74ZfwFY_VGxg <http://email.imobdevtech.com/c/eJwtjsFugzAQRL8GbiDverG9Bw6Gxv9he-2ClChRRIry94G2ozmM5vBmZGRxkGK7jqzd5ctOrjPWTx1ZPXccZuqs9_McfNAULg2p9XZPUn76fL-1y0imCjlCUhBj1VKiQsualeHByiDtdVy27dFo32A4vO97_0_YSl5OytG2z_FZHtd3g5PCyNEmQrTpDMxCqRpAzBVM1RQpKywAIpUKMB-9-hOAUwMNMTJGMJwLmOSIxByvf_H997otr3SOfgCqKUa8>
SkypeID: ghanshyam.bhesaniya@imobdev.com <mailto:ghanshyam.bhesaniya@imobdev.com>
Office: +91-79-651-22300
United States: +1 (908) 301-6001








"PLEASE CONSIDER THE ENVIRONMENT BEFORE PRINTING THIS EMAIL"

**Comment by jigar-shethia01** [comment]
Hello,

We have checked and what we believe is that the push notification is not working as there might be the case that something is missed while performing firebase implementation for the app. We will suggest you to once review the implementation as per the guidelines provided in https://developer.cometchat.com/docs/ios-push-notifications (refer **point no. 9**). This will resolve your issue.
If this is not helping then you can schedule a session form link below, we will be happy to help you. 
https://www.cometchat.com/schedule-session/

Thanks.

**Comment by IMDGhanshyam** [comment]
Hello,

I had to go through with **https://firebase.google.com/docs/cloud-messaging/ios/client** and there is nothing to change in my code. 

I have sent the notification from Firebase and I was got.
But, Still not get any notification for messages from CometChat.

Please check the below attachments.
![firebase-sentnotification](https://user-images.githubusercontent.com/44672948/48824844-886ecd00-ed8b-11e8-92de-b3da5f4c9104.png)
![testnotification](https://user-images.githubusercontent.com/44672948/48824845-886ecd00-ed8b-11e8-9b1b-5e3d265e235c.png)

**Comment by anantgarg** [comment]
Hello,

As this seems to be an issue with implementation, please schedule a session and we will be happy to assist you regarding this:

https://www.cometchat.com/schedule-session/
