### ISSUE TITLE
Image url does not set in Avatar 

### ISSUE THREAD

**Issue by IMDGhanshyam** [anantgarg/ios-objective-c-chat-sdk-demo#7]
-(void)registerUserOnCometChat:(NSString*)strUID userName:(NSString*)name profileImage:(NSString*)imgURL {
 
    //NSString *profileURL = @"";
    NSString *role = @"";
    NSLog(@"profileImage : %@",imgURL );
    [self.cometChat createUser:strUID userName:name avatarUrl:imgURL profileUrl:imgURL role:role success:^(NSDictionary *response) {
        
        NSLog(@"User Created Successfully %@",response);
        [self loginIntoCometChat];
        
    } failure:^(NSError *error) {
        NSLog(@"Failed %@",error);
    }];
}

![screenshot 2018-11-28 at 12 31 45 pm](https://user-images.githubusercontent.com/44672948/49134586-10178700-f30a-11e8-92e2-78d038149293.png)

**Comment by vikrantwadate** [comment]
Hello,

Thanks for writing in.

We have tested the mentioned scenario and it is encountered. We have fixed it and it will be available in the next release. You will be notified once it is released.

Thank you.

**Comment by vikrantwadate** [comment]
Hello,

We have fixed the issue. We request you to update to the latest SDK v7.23.0 and test the same.

Let us know your feedback.

Thank you.

**Comment by IMDGhanshyam** [comment]
This is still not resolved in the latest version.
please check this 

http://18.185.251.111/upload/users/488/profile1545378841102.jpeg

![screenshot 2018-12-21 at 4 45 34 pm](https://user-images.githubusercontent.com/44672948/50340180-fd2a5800-053f-11e9-8fcf-e825cf2f24d7.png)
![screenshot 2018-12-21 at 4 45 03 pm](https://user-images.githubusercontent.com/44672948/50340181-fd2a5800-053f-11e9-9a36-1981658aac60.png)


 
![screenshot 2018-12-21 at 4 58 42 pm](https://user-images.githubusercontent.com/44672948/50340616-b9385280-0541-11e9-99fd-df5c31cd8bff.png)

**Comment by vikrantwadate** [comment]
Hello,

The issue is resolved. However, it seems that you have used the avatarUrl as a profileUrl. You cannot use the avatarUrl for profileUrl.

We request you to try again with correct parameters.

Thanks.
