### ISSUE TITLE
Take time to load comet chat

### ISSUE THREAD

**Issue by IMDGhanshyam** [anantgarg/ios-objective-c-chat-sdk-demo#8]
When I click on the Chat Icon in the upper left, it takes approximately 6 seconds to load the Chat Screen. This is too long for a user to wait, how can we make this quicker?

Here is the method of for open Comet Chat.
-(void)launchCometChat:(UIViewController*)launchController {
    
    BOOL isFullScreen = YES;
    [SVProgressHUD show];
    
    [self.readyUIFileObject launchCometChat:isFullScreen observer:launchController userInfo:^(NSDictionary *response) {
        [SVProgressHUD dismiss];
        NSLog(@"launchCometChat Response : %@",response);
        NSString *pushChannel = [response valueForKey:@"push_channel"];
        [[FIRMessaging messaging] subscribeToTopic:pushChannel];
        
    } groupInfo:^(NSDictionary *response) {
        [SVProgressHUD dismiss];
        NSLog(@"groupInfo Response : %@",response);
        
    } onMessageReceive:^(NSDictionary *response) {
        [SVProgressHUD dismiss];
        NSLog(@"onMessageReceive Response : %@",response);
    } success:^(NSDictionary *response) {
        [SVProgressHUD dismiss];
        NSLog(@"success Response : %@",response);
        
    } failure:^(NSError *error) {
        
        NSLog(@"failure error : %@",error);
        [SVProgressHUD dismiss];
    } onLogout:^(NSDictionary *response) {
        [SVProgressHUD dismiss];
        NSLog(@"onLogout Response : %@",response);
    } ];
}

![ezgif-3-0c43b291c23c](https://user-images.githubusercontent.com/44672948/49492236-80c82180-f87d-11e8-9916-7edcb5d1f557.gif)

**Comment by vikrantwadate** [comment]
Hello,

We have started working on the concern raised by you with utmost priority. We will keep you posted on the progress and let you know once done.

Thanks.

**Comment by jigar-shethia01** [comment]
Hello,

We have fixed the issue you are facing. Please update to the latest SDK v7.24.0 this will resolve your issue. Please let us know your feedback. 

Thanks.
