### ISSUE TITLE
Change icons on bottom bar.

### ISSUE THREAD

**Issue by IMDGhanshyam** [anantgarg/ios-objective-c-chat-sdk-demo#9]
Can we change the icons of bottom bar?

![slide 3](https://user-images.githubusercontent.com/44672948/49568211-539b7200-f956-11e8-9338-17879a9824a0.png)

**Comment by jigar-shethia01** [comment]
Hello,

Please refer to the attached documentation. This will resolve the issues you are facing.
Do let us know if you are still facing any issue. We'll be glad to assist you.

Thanks.

[Documentation.docx](https://github.com/CometChat/ios-objective-c-chat-sdk-demo/files/2657478/Documentation.docx)
